name: Fetch AWS Secret on PR

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::672491114190:role/test
          aws-region: us-east-1

      - name: Fetch secret from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            MY_SECRET,arn:aws:secretsmanager:us-east-1:672491114190:secret:/playground/github-actions/test-ZxccUm

      - name: Write secret to file and print
        run: |
          printf '%s' "$MY_SECRET" > /tmp/secret.txt
          cat /tmp/secret.txt
