name: Fetch AWS Secret on PR

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::672491114190:role/test
          aws-region: us-east-1

      - name: Retrieve secret from AWS Secrets Manager
        id: aws-secrets
        run: |
          secrets=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:672491114190:secret:/playground/github-actions/test-ZxccUm --query SecretString --output text)
          my_secret="$(echo "$secrets" | jq .MY_SECRET_BASE64 -r | base64 -d)"
          echo "::add-mask::$(echo "$my_secret" | sed ':a;N;$!ba;s/%/%25/g' | sed ':a;N;$!ba;s/\r/%0D/g' | sed ':a;N;$!ba;s/\n/%0A/g')"
          echo "my-secret<<__EOF__"$'\n'"$my_secret"$'\n__EOF__' >> "$GITHUB_OUTPUT"

      - name: Write secret to file and print
        run: |
          printf '%s' "${{ steps.aws-secrets.outputs.my-secret }}" > /tmp/secret.txt
          cat /tmp/secret.txt
